import path from 'node:path';
import { readFile, readdir, unlink } from 'node:fs/promises';
import { listsDir } from '../config';
import { parse, stringify } from './frontmatter';
import { atomicWriteText } from './writer';
import { getDistinctLists, getRestaurantNamesForList } from '../db/queries';
import { log } from '../log';

const SENTINEL = {
	generated_by: 'restauranteer',
	do_not_edit: true,
	schema_version: 1
} as const;

// Fields preserved across MOC regenerations. These hold list-level metadata
// (notes, icon, source URL, imported timestamp) — anything else in the
// frontmatter gets overwritten by SENTINEL + list_name on each rewrite.
const PRESERVED_META_FIELDS = [
	'notes',
	'icon',
	'source_url',
	'imported_at',
	'created_manually'
] as const;

export type ListMeta = {
	notes: string | null;
	icon: string | null;
	source_url: string | null;
	imported_at: string | null;
};

export type ListSummary = { name: string; count: number };

type MocInfo = {
	filePath: string;
	listName: string;
	createdManually: boolean;
	meta: ListMeta;
};

function mocPath(listName: string): string {
	return path.join(listsDir(), `${listName}.md`);
}

export function isMocFile(filePath: string): boolean {
	return filePath.includes(`${path.sep}_Lists${path.sep}`) && filePath.endsWith('.md');
}

function pickStringField(
	frontmatter: Record<string, unknown>,
	key: string
): string | null {
	const v = frontmatter[key];
	return typeof v === 'string' && v.length > 0 ? v : null;
}

async function readMocInfo(filePath: string): Promise<MocInfo | null> {
	try {
		const { frontmatter } = parse(await readFile(filePath, 'utf8'));
		if (frontmatter.generated_by !== 'restauranteer') return null;
		if (typeof frontmatter.list_name !== 'string' || frontmatter.list_name.trim().length === 0) {
			return null;
		}
		return {
			filePath,
			listName: frontmatter.list_name.trim(),
			createdManually: frontmatter.created_manually === true,
			meta: {
				notes: pickStringField(frontmatter, 'notes'),
				icon: pickStringField(frontmatter, 'icon'),
				source_url: pickStringField(frontmatter, 'source_url'),
				imported_at: pickStringField(frontmatter, 'imported_at')
			}
		};
	} catch {
		return null;
	}
}

async function readMocFrontmatter(filePath: string): Promise<Record<string, unknown>> {
	try {
		const { frontmatter } = parse(await readFile(filePath, 'utf8'));
		return frontmatter as Record<string, unknown>;
	} catch {
		return {};
	}
}

async function readMocInfoForList(listName: string): Promise<MocInfo | null> {
	return readMocInfo(mocPath(listName));
}

async function listMocInfos(): Promise<MocInfo[]> {
	let entries: string[];
	try {
		entries = await readdir(listsDir());
	} catch (err) {
		const e = err as NodeJS.ErrnoException;
		if (e.code === 'ENOENT') return [];
		throw err;
	}
	const infos: MocInfo[] = [];
	for (const name of entries) {
		if (!name.endsWith('.md')) continue;
		const info = await readMocInfo(path.join(listsDir(), name));
		if (info) infos.push(info);
	}
	return infos;
}

async function writeMocContent(
	listName: string,
	names: string[],
	createdManually: boolean
): Promise<void> {
	const body = [
		'<!-- This file is generated by Restauranteer. Edits will be reverted. -->',
		'',
		`# ${listName}`,
		'',
		...(names.length > 0 ? names.map((n) => `- [[${n}]]`) : ['No restaurants yet.']),
		''
	].join('\n');
	const filePath = mocPath(listName);

	// Preserve user-set metadata fields (notes, icon, source_url, imported_at)
	// across regenerations. SENTINEL + list_name + createdManually always win.
	const preserved: Record<string, unknown> = {};
	const existingFm = await readMocFrontmatter(filePath);
	for (const f of PRESERVED_META_FIELDS) {
		if (f === 'created_manually') continue;
		if (typeof existingFm[f] !== 'undefined') preserved[f] = existingFm[f];
	}

	const fm = {
		...SENTINEL,
		list_name: listName,
		created_manually: createdManually || undefined,
		...preserved
	};
	const content = stringify(fm, body);

	try {
		const existing = await readFile(filePath, 'utf8');
		if (existing === content) return;
	} catch {
		// File doesn't exist yet
	}

	await atomicWriteText(filePath, content);
	log.debug('Regenerated MOC', { listName, count: names.length });
}

export async function hasListShell(listName: string): Promise<boolean> {
	const info = await readMocInfoForList(listName);
	return info?.createdManually === true;
}

export async function createEmptyListMoc(listName: string): Promise<void> {
	const names = getRestaurantNamesForList(listName);
	if (names.length > 0) {
		await writeMocForList(listName);
		return;
	}
	await writeMocContent(listName, [], true);
}

export async function getAllListSummaries(): Promise<ListSummary[]> {
	const byKey = new Map<string, ListSummary>();
	for (const list of getDistinctLists()) {
		byKey.set(list.name.toLowerCase(), list);
	}
	for (const info of await listMocInfos()) {
		const key = info.listName.toLowerCase();
		if (info.createdManually && !byKey.has(key)) {
			byKey.set(key, { name: info.listName, count: 0 });
		}
	}
	return [...byKey.values()].sort((a, b) =>
		a.name.localeCompare(b.name, undefined, { sensitivity: 'base' })
	);
}

export async function writeMocForList(listName: string): Promise<void> {
	const names = getRestaurantNamesForList(listName);
	const filePath = mocPath(listName);
	const existing = await readMocInfoForList(listName);
	if (names.length === 0) {
		if (existing?.createdManually) {
			await writeMocContent(listName, [], true);
			return;
		}
		try {
			await unlink(filePath);
			log.debug('Removed empty MOC', { listName });
		} catch {
			// ignore missing
		}
		return;
	}
	await writeMocContent(listName, names, existing?.createdManually === true);
}

/** Read list-level metadata (notes, icon, source_url, imported_at) from the
 * MOC file. Returns null if no MOC exists or it has no metadata. */
export async function getListMetadata(listName: string): Promise<ListMeta | null> {
	const info = await readMocInfoForList(listName);
	if (!info) return null;
	const { notes, icon, source_url, imported_at } = info.meta;
	if (notes == null && icon == null && source_url == null && imported_at == null) return null;
	return info.meta;
}

/** Stamp list-level metadata on the MOC. Creates the MOC if it doesn't exist
 * yet (lists with no restaurants still get a shell). Existing field values are
 * preserved unless explicitly overwritten by the input. */
export async function setListMetadata(
	listName: string,
	meta: Partial<ListMeta>
): Promise<void> {
	const filePath = mocPath(listName);
	const existingFm = await readMocFrontmatter(filePath);
	const merged: Record<string, unknown> = { ...existingFm };
	for (const [k, v] of Object.entries(meta)) {
		if (v == null || v === '') delete merged[k];
		else merged[k] = v;
	}

	const names = getRestaurantNamesForList(listName);
	const createdManually = merged.created_manually === true || names.length === 0;
	const body = [
		'<!-- This file is generated by Restauranteer. Edits will be reverted. -->',
		'',
		`# ${listName}`,
		'',
		...(names.length > 0 ? names.map((n) => `- [[${n}]]`) : ['No restaurants yet.']),
		''
	].join('\n');

	const fm = {
		...SENTINEL,
		list_name: listName,
		created_manually: createdManually || undefined,
		...Object.fromEntries(
			PRESERVED_META_FIELDS.filter((f) => f !== 'created_manually').map((f) => [f, merged[f]])
		)
	};
	const content = stringify(fm, body);
	await atomicWriteText(filePath, content);
	log.debug('Set list metadata', { listName, fields: Object.keys(meta) });
}

export async function regenerateAllMocs(): Promise<void> {
	const activeLists = new Map(getDistinctLists().map((l) => [l.name.toLowerCase(), l.name]));
	const mocs = await listMocInfos();
	const targetLists = new Map(activeLists);
	for (const info of mocs) {
		if (info.createdManually && !targetLists.has(info.listName.toLowerCase())) {
			targetLists.set(info.listName.toLowerCase(), info.listName);
		}
	}

	// Remove MOCs for lists that no longer have any restaurants
	for (const info of mocs) {
		if (!activeLists.has(info.listName.toLowerCase()) && !info.createdManually) {
			try {
				await unlink(info.filePath);
				log.debug('Removed stale MOC', { listName: info.listName });
			} catch {
				// ignore
			}
		}
	}

	for (const listName of targetLists.values()) {
		await writeMocForList(listName);
	}
}
