import path from 'node:path';
import { readFile, readdir, unlink } from 'node:fs/promises';
import { listsDir } from '../config';
import { stringify } from './frontmatter';
import { atomicWriteText } from './writer';
import { getDistinctLists, getRestaurantNamesForList } from '../db/queries';
import { log } from '../log';

const SENTINEL = {
	generated_by: 'restauranteer',
	do_not_edit: true,
	schema_version: 1
} as const;

function mocPath(listName: string): string {
	return path.join(listsDir(), `${listName}.md`);
}

export function isMocFile(filePath: string): boolean {
	return filePath.includes(`${path.sep}_Lists${path.sep}`) && filePath.endsWith('.md');
}

export async function writeMocForList(listName: string): Promise<void> {
	const names = getRestaurantNamesForList(listName);
	const filePath = mocPath(listName);
	if (names.length === 0) {
		try {
			await unlink(filePath);
			log.debug('Removed empty MOC', { listName });
		} catch {
			// ignore missing
		}
		return;
	}
	const body = [
		'<!-- This file is generated by Restauranteer. Edits will be reverted. -->',
		'',
		`# ${listName}`,
		'',
		...names.map((n) => `- [[${n}]]`),
		''
	].join('\n');
	const fm = { ...SENTINEL, list_name: listName };
	const content = stringify(fm, body);

	try {
		const existing = await readFile(filePath, 'utf8');
		if (existing === content) return;
	} catch {
		// File doesn't exist yet
	}

	await atomicWriteText(filePath, content);
	log.debug('Regenerated MOC', { listName, count: names.length });
}

export async function regenerateAllMocs(): Promise<void> {
	const activeLists = new Set(getDistinctLists().map((l) => l.name));

	// Remove MOCs for lists that no longer have any restaurants
	try {
		const entries = await readdir(listsDir());
		for (const name of entries) {
			if (!name.endsWith('.md')) continue;
			const listName = name.slice(0, -3);
			if (!activeLists.has(listName)) {
				try {
					await unlink(path.join(listsDir(), name));
					log.debug('Removed stale MOC', { listName });
				} catch {
					// ignore
				}
			}
		}
	} catch (err) {
		const e = err as NodeJS.ErrnoException;
		if (e.code !== 'ENOENT') throw err;
	}

	for (const listName of activeLists) {
		await writeMocForList(listName);
	}
}
