import path from 'node:path';
import { readFile, readdir, unlink } from 'node:fs/promises';
import { listsDir } from '../config';
import { parse, stringify } from './frontmatter';
import { atomicWriteText } from './writer';
import { getDistinctLists, getRestaurantNamesForList } from '../db/queries';
import { log } from '../log';

const SENTINEL = {
	generated_by: 'restauranteer',
	do_not_edit: true,
	schema_version: 1
} as const;

export type ListSummary = { name: string; count: number };

type MocInfo = {
	filePath: string;
	listName: string;
	createdManually: boolean;
};

function mocPath(listName: string): string {
	return path.join(listsDir(), `${listName}.md`);
}

export function isMocFile(filePath: string): boolean {
	return filePath.includes(`${path.sep}_Lists${path.sep}`) && filePath.endsWith('.md');
}

async function readMocInfo(filePath: string): Promise<MocInfo | null> {
	try {
		const { frontmatter } = parse(await readFile(filePath, 'utf8'));
		if (frontmatter.generated_by !== 'restauranteer') return null;
		if (typeof frontmatter.list_name !== 'string' || frontmatter.list_name.trim().length === 0) {
			return null;
		}
		return {
			filePath,
			listName: frontmatter.list_name.trim(),
			createdManually: frontmatter.created_manually === true
		};
	} catch {
		return null;
	}
}

async function readMocInfoForList(listName: string): Promise<MocInfo | null> {
	return readMocInfo(mocPath(listName));
}

async function listMocInfos(): Promise<MocInfo[]> {
	let entries: string[];
	try {
		entries = await readdir(listsDir());
	} catch (err) {
		const e = err as NodeJS.ErrnoException;
		if (e.code === 'ENOENT') return [];
		throw err;
	}
	const infos: MocInfo[] = [];
	for (const name of entries) {
		if (!name.endsWith('.md')) continue;
		const info = await readMocInfo(path.join(listsDir(), name));
		if (info) infos.push(info);
	}
	return infos;
}

async function writeMocContent(
	listName: string,
	names: string[],
	createdManually: boolean
): Promise<void> {
	const body = [
		'<!-- This file is generated by Restauranteer. Edits will be reverted. -->',
		'',
		`# ${listName}`,
		'',
		...(names.length > 0 ? names.map((n) => `- [[${n}]]`) : ['No restaurants yet.']),
		''
	].join('\n');
	const fm = { ...SENTINEL, list_name: listName, created_manually: createdManually || undefined };
	const content = stringify(fm, body);
	const filePath = mocPath(listName);

	try {
		const existing = await readFile(filePath, 'utf8');
		if (existing === content) return;
	} catch {
		// File doesn't exist yet
	}

	await atomicWriteText(filePath, content);
	log.debug('Regenerated MOC', { listName, count: names.length });
}

export async function hasListShell(listName: string): Promise<boolean> {
	const info = await readMocInfoForList(listName);
	return info?.createdManually === true;
}

export async function createEmptyListMoc(listName: string): Promise<void> {
	const names = getRestaurantNamesForList(listName);
	if (names.length > 0) {
		await writeMocForList(listName);
		return;
	}
	await writeMocContent(listName, [], true);
}

export async function getAllListSummaries(): Promise<ListSummary[]> {
	const byKey = new Map<string, ListSummary>();
	for (const list of getDistinctLists()) {
		byKey.set(list.name.toLowerCase(), list);
	}
	for (const info of await listMocInfos()) {
		const key = info.listName.toLowerCase();
		if (info.createdManually && !byKey.has(key)) {
			byKey.set(key, { name: info.listName, count: 0 });
		}
	}
	return [...byKey.values()].sort((a, b) =>
		a.name.localeCompare(b.name, undefined, { sensitivity: 'base' })
	);
}

export async function writeMocForList(listName: string): Promise<void> {
	const names = getRestaurantNamesForList(listName);
	const filePath = mocPath(listName);
	const existing = await readMocInfoForList(listName);
	if (names.length === 0) {
		if (existing?.createdManually) {
			await writeMocContent(listName, [], true);
			return;
		}
		try {
			await unlink(filePath);
			log.debug('Removed empty MOC', { listName });
		} catch {
			// ignore missing
		}
		return;
	}
	await writeMocContent(listName, names, existing?.createdManually === true);
}

export async function regenerateAllMocs(): Promise<void> {
	const activeLists = new Map(getDistinctLists().map((l) => [l.name.toLowerCase(), l.name]));
	const mocs = await listMocInfos();
	const targetLists = new Map(activeLists);
	for (const info of mocs) {
		if (info.createdManually && !targetLists.has(info.listName.toLowerCase())) {
			targetLists.set(info.listName.toLowerCase(), info.listName);
		}
	}

	// Remove MOCs for lists that no longer have any restaurants
	for (const info of mocs) {
		if (!activeLists.has(info.listName.toLowerCase()) && !info.createdManually) {
			try {
				await unlink(info.filePath);
				log.debug('Removed stale MOC', { listName: info.listName });
			} catch {
				// ignore
			}
		}
	}

	for (const listName of targetLists.values()) {
		await writeMocForList(listName);
	}
}
