import path from 'node:path';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { parse, stringify } from './frontmatter';
import { CURRENT_SCHEMA_VERSION, type Frontmatter } from './types';
import { readRestaurant } from './reader';
import { getRestaurantByUuid, getRestaurantNamesForList } from '../db/queries';
import { getDb } from '../db/schema';
import { restaurantsDir } from '../config';

let cachedAppVersion: string | null = null;

export const BUNDLE_MARKER = '<!-- restauranteer:file ';
const MARKER_LINE_RE = /^<!--\s*restauranteer:file\s+(.+?)\s*-->\s*$/;

export type ParsedBundleFile = {
	filename: string | null;
	rawContent: string;
	frontmatter: Frontmatter;
	body: string;
};

export type ParsedBundle = {
	info: Frontmatter | null;
	files: ParsedBundleFile[];
};

export function appVersion(): string {
	if (cachedAppVersion !== null) return cachedAppVersion;
	const candidates = [
		path.resolve(process.cwd(), 'package.json'),
		path.resolve(fileURLToPath(import.meta.url), '../../../../../package.json')
	];
	for (const file of candidates) {
		try {
			const json = JSON.parse(readFileSync(file, 'utf8')) as { name?: string; version?: string };
			if (json.name === 'restauranteer' && typeof json.version === 'string') {
				cachedAppVersion = json.version;
				return cachedAppVersion;
			}
		} catch {
			// try next candidate
		}
	}
	cachedAppVersion = '0.0.0';
	return cachedAppVersion;
}

/** Frontmatter emitted for `info.md` and at the top of a bundle. */
export function buildInfoFrontmatter(): Frontmatter {
	return {
		generated_by: 'restauranteer',
		app_version: appVersion(),
		schema_version: CURRENT_SCHEMA_VERSION,
		generated_at: new Date().toISOString()
	};
}

export function infoMarkdown(): string {
	const body = [
		'# About this vault',
		'',
		`This vault was generated by Restauranteer v${appVersion()}.`,
		`Schema version: ${CURRENT_SCHEMA_VERSION}.`,
		'',
		'Files in `Restaurants/` follow the restauranteer markdown format —',
		'each `.md` has YAML frontmatter (`id`, `name`, `lat`, `lng`, `cuisine`,',
		'`lists`, `tags`, `articles`, …) followed by free-form notes.',
		'',
		'See https://github.com/adamXbot/restauranteer for the schema.',
		''
	].join('\n');
	return stringify(buildInfoFrontmatter(), body);
}

/**
 * Build a multi-file bundle that another restauranteer can paste into Discover
 * to import several restaurants at once. The format is plain markdown with a
 * sentinel comment between files so it can also be inspected by a human.
 */
export function buildBundle(
	files: Array<{ filename: string; content: string }>,
	headerFrontmatter: Frontmatter | null = null
): string {
	const parts: string[] = [];
	const info = headerFrontmatter ?? buildInfoFrontmatter();
	parts.push(stringify(info, '# restauranteer bundle\n').trimEnd(), '');
	for (const f of files) {
		parts.push(`${BUNDLE_MARKER}${f.filename} -->`, '', f.content.trimEnd(), '');
	}
	return parts.join('\n').replace(/\n{3,}/g, '\n\n').trimEnd() + '\n';
}

/**
 * Parse a single restaurant markdown file or a multi-file bundle. Returns the
 * detected `info` frontmatter (from a bundle header or a standalone info.md)
 * plus one entry per restaurant file.
 */
export function parseBundle(text: string): ParsedBundle {
	const trimmed = text.replace(/^﻿/, '');
	if (!trimmed.includes(BUNDLE_MARKER)) {
		const { frontmatter, body } = parse(trimmed);
		if (looksLikeInfoOnly(frontmatter, body)) {
			return { info: frontmatter, files: [] };
		}
		return {
			info: null,
			files: [{ filename: null, rawContent: trimmed, frontmatter, body }]
		};
	}

	const lines = trimmed.split('\n');
	let info: Frontmatter | null = null;
	const files: ParsedBundleFile[] = [];
	let currentName: string | null = null;
	let buffer: string[] = [];
	let preamble: string[] | null = [];

	const flush = () => {
		if (currentName === null) {
			if (preamble && preamble.length > 0) {
				const preambleText = preamble.join('\n').replace(/^\s+/, '');
				const { frontmatter, body } = parse(preambleText);
				if (looksLikeInfoOnly(frontmatter, body) || isBundleHeader(frontmatter)) {
					info = frontmatter;
				}
			}
			preamble = null;
			buffer = [];
			return;
		}
		// gray-matter only recognises frontmatter when the document starts with
		// `---` on the very first line — strip leading blank lines that the
		// bundle separator inserts.
		const content = buffer.join('\n').replace(/^\s*\n/, '').trimEnd();
		if (content.length > 0) {
			const { frontmatter, body } = parse(content);
			files.push({ filename: currentName, rawContent: content, frontmatter, body });
		}
		buffer = [];
	};

	for (const line of lines) {
		const m = line.match(MARKER_LINE_RE);
		if (m) {
			flush();
			currentName = m[1];
			continue;
		}
		if (currentName === null) {
			if (preamble) preamble.push(line);
		} else {
			buffer.push(line);
		}
	}
	flush();

	return { info, files };
}

function looksLikeInfoOnly(fm: Frontmatter, body: string): boolean {
	if (fm.generated_by === 'restauranteer' && !fm.id) return true;
	if (!fm.id && !fm.name && body.length < 4000) return true;
	return false;
}

function isBundleHeader(fm: Frontmatter): boolean {
	return fm.generated_by === 'restauranteer' && !fm.id;
}

/** Read a single restaurant's markdown directly from disk via uuid. */
export async function readMarkdownByUuid(uuid: string): Promise<string | null> {
	const indexed = getRestaurantByUuid(uuid);
	if (!indexed) return null;
	const rf = await readRestaurant(indexed.file_path).catch(() => null);
	return rf?.rawContent ?? null;
}

/** Build a bundle for every restaurant in a list. */
export async function buildListBundle(listName: string): Promise<string> {
	const names = getRestaurantNamesForList(listName);
	const db = getDb();
	const files: Array<{ filename: string; content: string }> = [];
	for (const name of names) {
		const row = db
			.prepare(
				`SELECT r.file_path FROM lists l
				 JOIN restaurants r ON r.uuid = l.restaurant_uuid
				 WHERE l.list_name = ? AND r.name = ?
				 LIMIT 1`
			)
			.get(listName, name) as { file_path: string } | undefined;
		if (!row) continue;
		const rf = await readRestaurant(row.file_path).catch(() => null);
		if (!rf) continue;
		files.push({ filename: path.basename(row.file_path), content: rf.rawContent });
	}
	const header: Frontmatter = {
		...buildInfoFrontmatter(),
		list_name: listName,
		bundle_kind: 'list'
	};
	return buildBundle(files, header);
}

/** Compare two schema versions. Returns 0 if equal, 1 if `a` > `b`, -1 if a < b. */
export function compareSchemaVersions(a: number, b: number): -1 | 0 | 1 {
	if (a === b) return 0;
	return a > b ? 1 : -1;
}

export function vaultRoot(): string {
	return path.dirname(restaurantsDir());
}
